### ISSUE TITLE
Menu arrays are not Scalable

### ISSUE THREAD

**Issue by ayush-suman** [dvmappdassignments/git-github-and-kotlin-freshers2020#7]
@srijeet2310 @shikhar-dvm 
Your code doesn't support scalability of menu arrays. It would be better if the code works with menu arrays of all sizes.

**Comment by Shikhar1903** [comment]
@Ayush-Suman 
The class does not ask for scalability of menu items. The menu is pre-defined by the restaurant. If we want to add new dishes to the menu then  we just have to add one more element to the array which is not at all ambiguous. Adding a new dish by mutable arrays would just make it more complex.

**Comment by ayush-suman** [comment]
Cool..it's upto you ...Still it would have been better
We need the skill to program for scalable elements while developing apps for DVM
