### ISSUE TITLE
Syntax and Logical Error in code

### ISSUE THREAD

**Issue by Shikhar1903** [dvmappdassignments/git-github-and-kotlin-freshers2020#8]
@Ayush-Suman 
Your code has a minor syntax error preventing compilation.
When a dish is added more than one time(for eg. 2) then the bill displays the name of that dish twice, which should not be the case. A dish should be displayed in the bill once along with its quantity and total price.

**Comment by ayush-suman** [comment]
Where is the syntax error can you tell me..

I uploaded a working code and did some minor changes on GitHub 
Maybe then the syntax error would have creeped in.

I have purposely left the latter issue unresolved. It comes handy when one wants to view seperately ordered items seperately....

**Comment by PrarabdhGarg** [comment]
I would prefer you avoid making changes in code through gitHub.
When working on large projects, it could really be pretty hard

**Comment by ayush-suman** [comment]
Yes I will make a note of that. I will check and edit the code before Sat meet.
